### ISSUE TITLE
Favicon images for the same site do not cache

### ISSUE THREAD

**Issue by mike-healy** [andreasbm/web-skills#12]
Many resources reference the same domain (e.g. MDN at developer.mozilla.org), and therefore load the same favicon image.

However, because the full page URL is passed to plus.google.com/_/favicon each response is unique and the image is not cached.

This adds a lot of multi-second delays to fav icons being displayed.
I'd suggest changing the calls to load the fav icon to be the domain only, not full page URL so they share the response.

**Comment by andreasbm** [comment]
That's a fantastic idea, thank you so much for suggesting it 👍 I will make sure to include it in the next version.
