### ISSUE TITLE
Great work but let's not scare the cows

### ISSUE THREAD

**Issue by shellscape** [andreasbm/web-skills#14]
I think this is going to be a great resource for people moving forward.

But it's also being spread on Twitter as something that beginners and newcomers should reference. And with that I think there's some responsibility to the new generation (and even folks who have only been in this game a short while) to let them know that the content here is not something they're expected to know in total, but rather that these skills are learned over the course of a career.

With that, perhaps a banner, vanishing slide-down, or some other kind of noticeable alert to that effect could be added.

**Comment by andreasbm** [comment]
Hey Andrew! Thanks for opening this issue 👍 Great suggestion and a really valid point.

The intention of this project has never been to create "the complete roadmap" of web development skills. The idea is an has always been to create an overview of useful skills to learn as a web developer. I state the following on both the help page and in the Github readme.

### What is Web Skills?

> Web Skills is a visual overview of useful skills to learn as a web developer. It is useful for people who just started learning about web development and for people who have been in the field for years and want to learn new things. As a beginner, I would encourage you not to see this website as the definitive list of what you need to know but as an example of what you can learn and where you can start. The skills are arranged in chronological order based on what learning path I recommend you to take but feel free to jump around freely.

### How did you choose the skills?

> The skills are derived from a combination of 10 years of experience, a bachelor in software engineering and what I personally find to be the most useful to know on a day-to-day basis. Therefore, you'll notice that it's missing a lot of things. For example, I am not a PHP developer - because of this, PHP is not included. If you were a PHP developer, this overview would probably look a lot different.

### I am overwhelmed! Help me!

> I totally understand if you are a bit overwhelmed by the amount of skills on the page – but I can assure you that this overview includes much, much more than most people will ever need to know. My main goal is to provide a visual overview of web development and make people hungry for learning more. One of the things I absolute love about being a developer is learning new skills. I think it is amazing to be in a field where you can do what you do for a lifetime and still learn something new! People cannot be an expert in every skill on this page so try to find what excites you the most and become really good at that.

But apparently most people don't read that - and I can't blame them 🌞 I'll add an alert later today.

**Comment by andreasbm** [comment]
I just deployed a new version of the website with a banner when visiting the first time 🎉You might have to press "Reload" on the "New version" alert before you'll see the new banner. You are very welcome to give it a spin! Have a great day 👍

**Comment by shellscape** [comment]
Amazing, thank you!
