### ISSUE TITLE
The popup links are difficult to read

### ISSUE THREAD

**Issue by devgnx** [andreasbm/web-skills#29]
The links are written in blue with a dark background, is not a good combination due to contrast issues.

**Comment by andreasbm** [comment]
Thanks for opening this issue!

In the next version of Web Skills the color of the links have been changed so they now pass the WCAG 2.0 level AA requirements for normal text - previously they only passed these requirements for large text which I agree could be improved. You can find the new link color [here](https://webaim.org/resources/contrastchecker/?fcolor=5C85FF&bcolor=0B0B19). I expect these changes to go live tomorrow.

Have a great day!
