### ISSUE TITLE
Typo in ARIA item (Accessibility part)

### ISSUE THREAD

**Issue by lenakovaleva** [andreasbm/web-skills#33]
Hello, Andreas! 

Just got to know your work on web skills. It is amazing! Thank you very much for such a beautiful thing you made.

I saw a typo there and want to contribute a little bit. It is in the Accessibility part, ARIA item. Screenshot attached.

<img width="491" alt="typo" src="https://user-images.githubusercontent.com/13571254/80723271-a0bf4b80-8b2a-11ea-8323-b024da017a66.png">

**Comment by andreasbm** [comment]
Hey Lena! Thanks a lot for opening this issue 👍 I'm really glad that you like Web Skills!

Well spotted, I've fixed the typo for the next version. 

Have a great day 🌞

**Comment by lenakovaleva** [comment]
Hi, thanks a lot!
Have a great day too!
