### ISSUE TITLE
Url to start in compact mode

### ISSUE THREAD

**Issue by Slaviusz** [andreasbm/web-skills#5]
It would be nice to provide and url to start in compact mode by default (?compact=true or #compact).

Thanks for considering.

**Comment by andreasbm** [comment]
Thanks for opening this issue. Brilliant idea! ✨

I just implemented this functionality and it should be up and running. Check it out at https://andreasbm.github.io/web-skills/?compact. I might make the compact mode default in the future.

Have a great day.
