### ISSUE TITLE
Wrong Icon on Servo Browser Engine

### ISSUE THREAD

**Issue by puresick** [andreasbm/web-skills#8]
The icon for the Servo Browser engine is wrong. It is a new Engine developed by Mozilla and part of it (the CSS Engine) is being used in the current Firefox (since version 57).
Opera, which icon is being used currently, is based on chromium and therefore on the blink engine.

**Comment by andreasbm** [comment]
Thanks a lot for opening this issue!

I have corrected it and deployed a new version 👍

Have a great day 🌞
